### ISSUE TITLE
Bug: Downloading images overlap network and DCT

### ISSUE THREAD

**Issue by Irisdenis** [ErwinKomen/RU-passim#758] opened 2024-05-16 16:33 UTC
Some of the editors are having trouble with downloading images of both the overlap network **from the second level and higher**, and the **DCT as a whole**. Instead of downloading, there’s a ‘server error 505’. 

I had the same experience yesterday, but today the functions seem to work again for me; other PASSIM editors still get the same error. Any idea what might cause this? How can we prevent it?

**Comment by ErwinKomen** [comment] 2024-05-22 06:25
This error cannot be reproduced. When it occurs again, please email us the date and time that this happened. Then we can check in the log files what is the matter.

**Comment by ErwinKomen** [comment] 2024-05-22 09:53
Possible cause: code update while the user was working?
Closing this issue, since everything seems to work alright now.

**Comment by Irisdenis** [comment] 2024-05-29 08:02
Update: the problem might be the downloading in the _Safari_ browser?
PI tested the downloading of an image of the DCT on 29-05, 9:55, which failed and resulted in a server error like the one above.
Downloading of images from the overlap network worked as it should (this time).

The problem seems to occur infrequently. Can you see if it _is_ connected to the use of Safari browser?

**Comment by ErwinKomen** [comment] 2024-05-29 08:27
I looked in the LOG files, and there is nothing unusual there (the commands just executed normally).
We are **not** able to check whether something works well on the Safari browser, since we don't have access to an apple computer.
One thing to try: **refresh** (equivalent of Ctrl +F5 on Windows).
(Internet says: `For Mac, hold Cmd+Shift+R or Shift+Reload`)

Alternatives:
1. Use a non-Safari browser on the Apple computer
2. Let me have a look at what happens on this Apple computer (EK: see [developer mode](https://support.apple.com/nl-nl/guide/safari/sfri20948/mac))

**Closed** 2024-06-12 08:21 UTC
Labels: bug
